<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl=$storeManager->getStore()->getBaseUrl();
$_product = $block->getProduct(); 
echo $_product->getAttributeText('user_manual');
echo $_product->getAttributeText('product_sheet');
 ?>
<div class="extra-details">
	<a target="_blank" class="faq" href="<?php echo $baseUrl.'faq'?>"><span>FAQ's</span></a>
	<?php if($_product->getUserManual()){ ?><a target="_blank" class="user-manual" href="<?php echo $_product->getUserManual() ?>"><span>User Manual</span></a><?php } ?> 
	<?php if($_product->getProductSheet()){ ?><a target="_blank" class="product-sheet" href="<?php echo $_product->getProductSheet() ?>"><span>Product Sheet</span></a><?php } ?>
</div>