<?php


$itemsJsonData = $block->getDataOneColumnJson();
?>

<div class="faq-container">
    <div class="faq-list" data-bind="scope: 'faq-grid'">

        <!-- ko template: getTemplate() --><!-- /ko -->

    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "faq-grid": {
                    "component": "Acodez_Faq/js/faq/1column/grid"
                }
            }
        }
    }
}
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Acodez_Faq/js/faq/1column/grid": {
                "items": <?php /* @escapeNotVerified */ echo $itemsJsonData; ?>
            }
        }
    }
</script>