
<?php
$catid =$this->getCategory();
 $Homeslides=$block->getCategoryHomeSlides($catid);

$mediaUrl=$block->getMediaUrl();
$sliderNames=array();$sliderIcons=array();
if($block->isEnabled()){
?>

 <div  id="banners">
  <div class="slick-slider1">
    <?php foreach ($Homeslides as $Homeslide){ ?>
    <?php if($Homeslide){
      $sliderNames[]=$Homeslide->getName();
      $sliderIcons[]=$Homeslide->getIcon();
      $darkMode=$Homeslide->getDarkMode();
      if($darkMode==1){
        $darkClass='darkbg';

      }else{
         $darkClass='lightbg';
      }
      $bgImage=$mediaUrl.$Homeslide->getBgImage();

       ?>
       <div class="slider-contents" data-color="<?php echo $darkClass;?>">
        <div class="homeslides" style="background-color: #<?php echo $Homeslide->getBgColor()?>; background-image:url(<?php echo $bgImage;?>);background-size:cover;background-repeat: no-repeat;">
          <div class="home-slide-cnt">
              <?php if($Homeslide->getDescription()){ ?>
               <div class="slide-content">
                 <?php echo $Homeslide->getDescription()?>
               </div>
                <?php } ?>
              <?php if($Homeslide->getSlideUrl()){ ?>
                    <a href="<?php echo $Homeslide->getSlideUrl();?>" class="slide-img">
              <?php } ?>
              <picture>
          <source media="(min-width: 640px)" srcset="<?php echo $mediaUrl.$Homeslide->getDesktopImage();?>">
          <img src="<?php echo $mediaUrl.$Homeslide->getMobileImage();?>"  style="width:auto;" alt="<?php if($Homeslide->getName()){ echo $Homeslide->getName(); }else{ echo 'slide'; } ?>">
        </picture>
        <?php if($Homeslide->getSlideUrl()){ ?>
            </a>
            <?php } ?>
          </div>
      </div>
  </div>
    <?php } } ?>
  </div>
  <!-- Add Pagination -->
<!-- <div class="swiper-pagination"></div> -->



</div>


 <script>


    require(['jquery','slick'], function($) {

var sliderName1 = <?php echo json_encode($sliderNames) ?>;
var sliderIcon = <?php echo json_encode($sliderIcons) ?>;
            $('.slick-slider1').on('init', function(event, slick){
                var color = $('.slick-current').find(".slider-contents").attr("data-color"); 
                $(".sections.nav-sections").removeClass("lightbg darkbg");
                $(".page-header").removeClass("lightbg darkbg");
                $(".sections.nav-sections").addClass(color);  
                $(".page-header").addClass(color); 
                
            });
           $('.slick-slider1').slick({
              infinite: true,
              arrows: false,
              slidesToShow:1,
              autoplay: true,
              loop:true,
              fade: true,
              slidesToScroll: 1,
              vertical:false,
              easing: 'swing',
              speed: 1000,
              autoplaySpeed:5000,
              pauseOnHover:false,
               dots: true,
               customPaging: function(slick,index) {
               var html= '<div class="slidernav">';
               if(sliderIcon[index]){
            
                html+='<span class="icon" style="background: url(<?php echo $mediaUrl;?>'+sliderIcon[index]+')"></span>';
               }
               html+='<h4>'+sliderName1[index]+'</h4></div>' ;
                  return html;
              }
            });
            $('.slick-dots li').on('mouseover', function() {
                  $(this).trigger('click');
            });
            $('.slick-slider1').on('afterChange', function(event, slick, currentSlide, nextSlide){
                var color = $('.slick-current').find(".slider-contents").attr("data-color"); 
                $(".sections.nav-sections").removeClass("lightbg darkbg");
                $(".page-header").removeClass("lightbg darkbg");
                $(".sections.nav-sections").addClass(color);  
                $(".page-header").addClass(color);     
            });
            

        });
</script>
<?php } ?>
